- name: Install GitLab EE
  hosts: gitlab-instance
  become: true

  pre_tasks:
    - name: Set SSH user and private key file for Ubuntu
      ansible.builtin.set_fact:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ./private_key.pem
      when: ansible_os_family == "Debian"

  tasks:
    - name: Update and Install the Dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: [curl, openssh-server, ca-certificates, tzdata, perl]

    - name: Add GitLab EE package repo
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash

    - name: Ensure the existance of /etc/gitlab directory
      file:
        path: /etc/gitlab
        state: directory

    - name: Copy gitlab.rb file
      copy:
        src: ./gitlab.rb
        dest: /etc/gitlab/gitlab.rb

    - name: Install GitLab EE package
      apt:
        name: gitlab-ee
        state: present
        update_cache: yes