name: Infrastructure CI/CD pipeline

on:
    push:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]

    pull_request:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]
    workflow_dispatch:

jobs:
  CI:
    
    permissions:
      actions: read
      contents: read
      id-token: write
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Init
        run: |
          cd infrastructure
          terraform init

      - name: Validate
        run: |
          cd infrastructure
          terraform validate

      - name: Install tfsec for scanning
        run:
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: scan
        run: |
          ls ~/go/bin/tfsec
          export PATH=$PATH:$HOME/go/bin
          tfsec
        continue-on-error: true

      - name: test
        run: |
          ls ~/.ssh
          ls -la ~/.ssh

      - name: plan
        run: |
          cd infrastructure
          terraform plan