name: Infrastructure CI/CD pipeline

on:
    push:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]

    pull_request:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]
    workflow_dispatch:

jobs:
  CI:
    
    permissions:
      actions: read
      contents: read
      id-token: write
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          cd infrastructure
          terraform init

      - name: Validate
        run: |
          pwd
          cd infrastructure
          terraform validate
          
      - name: plan
        run: |
          pwd
          cd infrastructure
          terraform plan