name: Infrastructure CI/CD pipeline

on:
    push:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]

    pull_request:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]
    workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: check terraform
        run: terraform version