name: Infrastructure CI/CD pipeline

on:
    push:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]

    pull_request:
        branches: [ "main" ]
        paths-ignore: ["**/*.md"]
    workflow_dispatch:

jobs:
  init:
    
    permissions:
      actions: read
      contents: read
      id-token: write
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          cd infrastructure
          terraform init